// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using creditcardapplication.Data;

#nullable disable

namespace creditcardapplication.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("creditcardapplication.Data.CreditCard", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpireDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("CardId");

                    b.ToTable("CreditCards");

                    b.HasData(
                        new
                        {
                            CardId = 1,
                            CardHolderName = "Frank Boateng 1",
                            CardNumber = "421024523562523 1",
                            CardType = "VISA 1",
                            ExpireDate = "10/25 1",
                            SecurityCode = "456 1"
                        },
                        new
                        {
                            CardId = 2,
                            CardHolderName = "Frank Boateng 2",
                            CardNumber = "421024523562523 2",
                            CardType = "VISA 2",
                            ExpireDate = "10/25 2",
                            SecurityCode = "456 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
